[package]
name = "sliding_features"
version = "0.2.0"
authors = ["MathisWellmann <wellmannmathis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rulinalg = "0.4.2"

[dev-dependencies]
rust_timeseries_generator = { git = "https://github.com/MathisWellmann/rust_timeseries_generator"}
rand = "0.7.3"
